version: '3'
services:
  app:
    build:
      context: . 
      dockerfile: ./Dockerfile.dev
    container_name: erp-web
    network_mode: "bridge"
    ports:
     - 3000:3000
    volumes:
      - .:/app
  