# Use a imagem Node.js como base
FROM node:18-alpine
# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app
RUN apk add --no-cache g++ make py3-pip libc6-compat
# Copie os arquivos do projeto para o contêiner
COPY . .

# Instale o Next.js
RUN npm install -g next@14.0.3
ENV NEXT_TELEMETRY_DISABLED 1
# Instale as dependências do projeto
RUN npm install

# Exponha a porta em que o servidor Next.js será executado
EXPOSE 3000

# Inicie o servidor Next.js no modo de desenvolvimento
CMD ["npm", "run", "dev"]
