import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Sidebar from './components/layout/Sidebar';
import Header from './components/layout/Header';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative h-screen overflow-hidden bg-gray-100 dark:bg-gray-800">
          <div className="flex items-start justify-between">
            <Sidebar />
            <div className="flex flex-col w-full md:space-y-4">
              <Header />
              <div className="h-screen px-4 pb-24 overflow-auto md:px-6">
                {children}
              </div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
